data_dir: /home/ace/Downloads/Dataset
save_dir: ./single_segmentation_outputs_mixed_deeplab
device: cuda
selection:
  image_name: null
  location_id: '878'
  illumination: Day
  weather: EXTRASUNNY
  pick_index: 0
model:
  key: deeplabv3plus_r101_local
  name: DeepLabV3+-R101
  type: deeplabv3plus_r101
  checkpoint_path: /home/ace/Downloads/models_weights/best_deeplabv3plus_resnet101_cityscapes_os16.pth
  input_source: repo
  input_norm: none
export:
  preview_figsize:
  - 12
  - 5
  preview_dpi: 200
  save_png_too: true
  save_raw_prediction_npy: true
  save_confidence_npy: false
