data_dir: /home/ace/Downloads/Dataset
save_dir: ./single_segmentation_outputs_mixed_hf
device: cuda
selection:
  image_name: null
  location_id: '878'
  illumination: Day
  weather: EXTRASUNNY
  pick_index: 0
model:
  key: segformer_b5
  name: SegFormer-B5
  type: segformer
  model_id: nvidia/segformer-b5-finetuned-cityscapes-1024-1024
  input_source: raw
export:
  preview_figsize:
  - 12
  - 5
  preview_dpi: 200
  save_png_too: true
  save_raw_prediction_npy: true
  save_confidence_npy: false
