seed: 0
data_dir: /home/ace/Downloads/Dataset
save_dir: ./out_cityscapes_final_notebook
device: cuda
batch_size: 2
num_workers: 4

conf_threshold: 0.6
mass_coverage: 0.99
n_qual_samples: 6
plot_scenarios:
  - Day-RAIN
  - Sunset-FOGGY
  - Night-RAIN
plot_drop_classname: train

# Qualitative visualization model
qual_model_key: segformer_b5

#Modular model configuration.
models:
  enabled:
    - segformer_b0
    - segformer_b2
    - segformer_b5
    - mask2former_swin_s
    - mask2former_swin_l

    - key: deeplabv3plus_r101_local
      checkpoint_path: /home/ace/Downloads/models_weights/best_deeplabv3plus_resnet101_cityscapes_os16.pth
      input_norm: none

    - key: pidnet_m_local
      checkpoint_path: /home/ace/Downloads/models_weights/PIDNet_M_Cityscapes_val.pt
      input_norm: imagenet

    - key: ddrnet23_official
      checkpoint_path: /home/ace/Downloads/models_weights/ddrnet23_cityscapes.pth
      input_norm: imagenet

   