input:
  image_path: "/home/ace/Downloads/test_image.png"

models:
  enabled:
    - key: segformer_b0

    - key: segformer_b2

    - key: segformer_b5

    - key: mask2former_swin_s

    - key: mask2former_swin_l

    - key: deeplabv3plus_r101_local
      checkpoint_path: /home/ace/Downloads/models_weights/best_deeplabv3plus_resnet101_cityscapes_os16.pth

    - key: pidnet_m_local
      checkpoint_path: /home/ace/Downloads/models_weights/PIDNet_M_Cityscapes_val.pt

    - key: ddrnet23_local
      checkpoint_path: /home/ace/Downloads/models_weights/ddrnet23_cityscapes.pth

output:
  save_dir: "./single_segmentation_outputs"

visualization:
  save_overlay: true
  save_mask: true
  save_panel: true

inference:
  device: "cuda"
